name: jpug-doc build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout jpug-doc
      uses: actions/checkout@v2
      with:
        repository: pgsql-jp/jpug-doc
        path: tmp-jpug-doc
    - name: Install Dependencies
      run: |
        sudo apt install -y docbook-xsl libbsd-dev libedit-dev libpam0g-dev libperl-dev libxml2-utils xsltproc fonts-takao-mincho fonts-takao-pgothic fonts-takao-gothic fop
    - name: Preparation of font
      run: |
        mkdir ~/.fonts/
        cp scripts/fonts/* ~/.fonts/
        fc-cache -f -v
    - name: build
      run: |
        cd tmp-jpug-doc
        ./configure
        cd doc/src/sgml
        make ORIGINAL=1 html
        make postgres-A4.pdf
